services:
  tubes-api:
    image: kanzen523/tubes:latest
    container_name: tubes
    restart: always # Always restart 
    ports:
      - "8080:8080" # Left side is host port, right side is container port
    env_file:
      - .env
    networks:
      - tubes-network

  postgres-dev:
    image: postgres:latest
    container_name: postgres-dev
    restart: always # Always restart 
    ports:
      - "5432:5432" # Left side is host port, right side is container port
    environment:
      POSTGRES_DB: tubes
      POSTGRES_USER: kanzen
      POSTGRES_PASSWORD: Prj977je94.
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tubes-network

volumes:
  postgres-data:

networks:
  tubes-network:
    driver: bridge
